---
- name: Install multiple packages
  hosts: all
  become: yes

  tasks:
    - name: Install git
      yum:
        name: git
        state: present

    - name: Install wget
      yum:
        name: wget
        state: present

    - name: Install curl
      yum:
        name: curl
        state: present		