---
- name: Use variables in tasks
  hosts: all
  become: yes

  vars:
    package_name: nginx

  tasks:
    - name: Install package
      yum:
        name: "{{ package_name }}"
        state: present

    - name: Start service
      service:
        name: "{{ package_name }}"
        state: started